substitutions:
  _IMAGE_NAME: "linux-builder"

steps:
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID"
      - "."

  - id: "tag-image"
    name: "gcr.io/cloud-builders/docker"
    env:
      - "IMAGE_NAME=gcr.io/$PROJECT_ID/$_IMAGE_NAME"
      - "BRANCH_NAME=$BRANCH_NAME"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -eu
        set -x

        version=$(docker inspect --format '{{ index .Config.Labels "version"}}' \
          "$$IMAGE_NAME:$BUILD_ID")

        if [[ "$$BRANCH_NAME" == "master" ]]; then
          for tag in "$$version" "latest"; do
            docker tag "$$IMAGE_NAME:$BUILD_ID" "$$IMAGE_NAME:$$tag"
            docker push "$$IMAGE_NAME:$$tag"
          done
        elif [[ "$$BRANCH_NAME" != "" ]]; then
          SAFE_BRANCH_NAME="${BRANCH_NAME//[^a-zA-Z0-9.-]/_}"
          for tag in "$$version-$$SAFE_BRANCH_NAME" "$$SAFE_BRANCH_NAME"; do
            docker tag "$$IMAGE_NAME:$BUILD_ID" "$$IMAGE_NAME:$$tag"
            docker push "$$IMAGE_NAME:$$tag"
          done
        fi

images:
  - "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID"
